-- DISABLE RLS - IMMEDIATE FIX
ALTER TABLE districts DISABLE ROW LEVEL SECURITY;
ALTER TABLE hospitals DISABLE ROW LEVEL SECURITY;
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;

-- Verify
SELECT 'RLS DISABLED - ERROR FIXED' as status;
