-- DISABLE ALL RLS - SAFE VERSION (only existing tables)
ALTER TABLE IF EXISTS districts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS hospitals DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS health_alerts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS appointments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS prescriptions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS lab_reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS inventory DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS disease_cases DISABLE ROW LEVEL SECURITY;

-- Verify
SELECT 'ALL RLS DISABLED' as status;
SELECT tablename, rowsecurity FROM pg_tables 
WHERE schemaname = 'public' 
AND rowsecurity = true;
